Proyecto Django/libranium/carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [

    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

Proyecto Django/libranium/libranium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('carro/', include('carro.urls')),
    path('accounts/', include('django.contrib.auth.urls'),)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Proyecto Django/libranium/carro/models.py
from django.db import models

# Create your models here.

Proyecto Django/libranium/carro/views.py
from django.shortcuts import render
from .carro import Carro

from app.models import Libro

from django.shortcuts import redirect
# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Libro.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("home")

def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Libro.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("home")

def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Libro.objects.get(id=producto_id)

    carro.restar(producto=producto)

    return redirect("home") 

def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("home")

Proyecto Django/libranium/app/templates/carro/widget.html
<table class="table table-bordered" style="color: black;">

    <thead>
        <tr>

            <th colspan="3" class="text-center">

                Carro de compras

            </th>

        </tr>
        
        <tr>
            <th>PRODUCTO</th>
            <th>CANTIDAD</th>
            <th>PRECIO</th>


        </tr>

    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.titulo}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url  'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url  'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br>

                        ${{value.precio}}
                    </td>
                </tr>

            {% endfor %}

        {% else %}
            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        SIN PRODUCTOS

                    </div>
                </td>
            </tr>

        {% endif %}

    </tbody>
    
    <tfoot>
        <tr>
            <td colspan="3">
                Total: ${{importe_total_carro}} 
            </td>
        </tr>
    </tfoot>


</table>