Proyecto Django/libranium/carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [

    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

Proyecto Django/libranium/libranium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('carro/', include('carro.urls')),
    path('accounts/', include('django.contrib.auth.urls'),)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

models.py
from django.db import models

# Create your models here.

class Libro(models.Model):
    titulo = models.CharField(max_length=50)
    autor = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    año_pub = models.CharField(max_length=4)
    editorial = models.CharField(max_length=50)
    encuadernacion = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="libros",null=True)

    def __str__(self):
        return self.titulo
    

class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    titulo = models.ForeignKey(Libro, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre

Proyecto Django/libranium/app/templates/app/Crec_Personal.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'app/CSS/miCss.css' %}">
  <link rel="stylesheet" href="{% static 'app/JS/carrito.js' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <title>Crecimiento Personal</title>
  <link rel="icon" href="{% static 'app/imagenes/Logo.png' %}">
</head>

<body>
  <!--nav bar-->
  <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'app/imagenes/Logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        Librarium
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Ofertas</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Categorias
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'juvenil' %}">Infantil y Juvenil</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Lit_Chilena' %}">Lit. Chilena</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Crec_Personal' %}">Crec. Personal</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'novelas' %}">Novelas</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'poesia' %}">Poesia</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Novedades</a>
          </li>
          {% if perms.app.add_libro %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Administracion
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'listar_productos' %}">listado producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'agregar_producto' %}">agregar producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
            {% endif %}
        </ul>
        <div class="iconos">
          <li class="cuenta">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" id="logbtn"><i class="bi bi-person-x" style="color:rgb(67, 68, 68);"></i></button>
            </form>
            {% else %}
              <a href="{% url 'login' %}"><i class="bi bi-person" style="color:rgb(67, 68, 68);"></i></a>
            {% endif %}
          </li>
          <li class="carro">
            <a href="#" id="carrito">
              <i class="bi bi-cart2" style="color:rgb(67, 68, 68);">
                  <div class="buy-card">
                    <ul class="nav-card">
                        <li id="carro__li">Imagen</li>
                        <li id="carro__li">Nombre</li>
                        <li id="carro__li">Precio</li>
                        <li id="carro__li">Cantidad</li>
                    </ul>
                    <div class="lista-de-compras">
                      
                    </div>
                    <button id="vaciar_carro">VACIAR CARRITO</button>
                  </div>
              </i>
            </a>
          </li>
        </div>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Buscar Titulo, Autor, Isbn..."
            aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>
      </div>
    </div>
  </nav>
  <!--fin navbar-->
    <br>
  <!--cards-->
  <div class="containers">
    <center>
      <h1 class="texto">Crecimiento Personal</h1>
    </center>
    <div class="card__container" id="lista-compra">
      <article class="card__article">
        <img src="{% static 'app/imagenes/habitos (1).jpg' %}" alt="" class="card__img">

        <div class="card__data">
          <span class="card__description">Stephen R. Covey</span>
          <h2 class="card__title">Los 7 hábitos de la gente altamente efectiva</h2>
          <p class="precio">$11.000</p>
          <a href="#" class="card__button">Mas info</a>
          <button class="card__button2" data-id="1">add to cart</button>
        </div>
      </article>

      <article class="card__article">
        <img src="{% static 'app/imagenes/invierte en ti.jpg' %}" alt="" class="card__img">

        <div class="card__data">
          <span class="card__description">Natalia de Santiago</span>
          <h2 class="card__title">Invierte en ti</h2>
          <p class="precio">$11.000</p>
          <a href="#" class="card__button">Mas info</a>
          <button class="card__button2" data-id="2">add to cart</button>
        </div>
      </article>

      <article class="card__article">
        <img src="{% static 'app/imagenes/focus (1).jpg' %}" alt="" class="card__img">

        <div class="card__data">
          <span class="card__description">Daniel Goleman</span>
          <h2 class="card__title">Focus</h2>
          <p class="precio">$11.000</p>
          <a href="#" class="card__button">Mas info</a>
          <button class="card__button2" data-id="3">add to cart</button>
        </div>
      </article>
    </div>
  </div>
  <!--fin cards-->
  <!--Footer-->
  <footer class="footer">
    <div class="container">
      <div class="footer-row">
        <div class="footer-links">
          <h4>Empresa</h4>
          <ul>
            <li><a href="{% url 'Nosotros' %}">Nosotros</a></li>
            <li><a href="#">Nuestros servicios</a></li>
            <li><a href="#">Politica de privacidad</a></li>
            <li><a href="{% url 'formulario' %}">Afiliate</a></li>
          </ul>
        </div>
        <div class="footer-links">
          <h4>Ayuda</h4>
          <ul>
            <li><a href="#">Preguntas Frecuentes</a></li>
            <li><a href="#">Compras</a></li>
            <li><a href="#">Envios</a></li>
            <li><a href="#">Pago</a></li>
          </ul>
        </div>
        <div class="footer-links">
          <h4>Encuentranos</h4>
          <ul>
            <li><a href="{% url 'ubicacion' %}">Av.Valparaiso 429</a></li>
            <li><a href="#">librarium@gmail.com</a></li>
            <li><a href="#"></a></li>
          </ul>
        </div>
        <div class="footer-links">
          <h4>Siguenos</h4>
          <div class="social-link">
            <a href="#"><i class="bi bi-facebook"></i></a>
            <a href="#"><i class="bi bi-whatsapp"></i></a>
            <a href="#"><i class="bi bi-twitter-x"></i></a>
            <a href="#"><i class="bi bi-instagram"></i></a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  
  
    <script src="{% static 'app/JS/carrito.js' %}"></script>
</body>

</html>

Proyecto Django/libranium/app/templates/app/comprar.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'app/CSS/miCss.css' %}">
  <link rel="stylesheet" href="{% static 'app/JS/carrito.js' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  <title>Inicio</title>
  <link rel="icon" href="{% static 'app/imagenes/Logo.png' %}">
</head>

<body>
  <!--nav bar-->
  <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'app/imagenes/Logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        Librarium
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#Ofertas">Ofertas</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Categorias
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'juvenil' %}">Infantil y Juvenil</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Lit_Chilena' %}">Lit. Chilena</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Crec_Personal' %}">Crec. Personal</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'novelas' %}">Novelas</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'poesia' %}">Poesia</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#Novedades">Novedades</a>
          </li>
          {% if perms.app.add_libro %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Administracion
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'listar_productos' %}">listado producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'agregar_producto' %}">agregar producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
            {% endif %}
            </ul>
          </li>
        </ul>
        <div class="iconos">
          
          <li class="cuenta">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-transparent"><i class="bi bi-person-x" style="color:rgb(67, 68, 68);"></i></button>
            </form>
            {% else %}
              <a href="{% url 'login' %}"><i class="bi bi-person" style="color:rgb(67, 68, 68);"></i></a>
            {% endif %}
          </li>
          <li class="carro">
            <a href="{% url 'comprar' %}" id="carrito">
              <i class="bi bi-cart2" style="color:rgb(67, 68, 68);">
              </i>
            </a>
          </li>
        </div>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Buscar Titulo, Autor, Isbn..."
            aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>
      </div>
    </div>
  </nav>


  <div class="container">
    <div style=" float:right;">
      
      {% include "carro/widget.html" %}
    </div>
  </div>
  

  <!--Footer-->
  <div>
    <footer class="footer">
      <div class="container">
        <div class="footer-row">
          <div class="footer-links">
            <h4>Empresa</h4>
            <ul>
              <li><a href="{% url 'Nosotros' %}">Nosotros</a></li>
              <li><a href="#">Nuestros servicios</a></li>
              <li><a href="#">Politica de privacidad</a></li>
              <li><a href="{% url 'formulario' %}">Afiliate</a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Ayuda</h4>
            <ul>
              <li><a href="#">Preguntas Frecuentes</a></li>
              <li><a href="#">Compras</a></li>
              <li><a href="#">Envios</a></li>
              <li><a href="#">Pago</a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Encuentranos</h4>
            <ul>
              <li><a href="{% url 'ubicacion' %}">Av.Valparaiso 429</a></li>
              <li><a href="#">librarium@gmail.com</a></li>
              <li><a href="#"></a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Siguenos</h4>
            <div class="social-link">
              <a href="#"><i class="bi bi-facebook"></i></a>
              <a href="#"><i class="bi bi-whatsapp"></i></a>
              <a href="#"><i class="bi bi-twitter-x"></i></a>
              <a href="#"><i class="bi bi-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <script src="{% static 'app/JS/carrito.js' %}"></script>
</body>

</html>

Proyecto Django/libranium/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'app/CSS/miCss.css' %}">
  <link rel="stylesheet" href="{% static 'app/JS/carrito.js' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  <title>Inicio</title>
  <link rel="icon" href="{% static 'app/imagenes/Logo.png' %}">
</head>

<body>
  <!--nav bar-->
  <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'app/imagenes/Logo.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        Librarium
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#Ofertas">Ofertas</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Categorias
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'juvenil' %}">Infantil y Juvenil</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Lit_Chilena' %}">Lit. Chilena</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'Crec_Personal' %}">Crec. Personal</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'novelas' %}">Novelas</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'poesia' %}">Poesia</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#Novedades">Novedades</a>
          </li>
          {% if perms.app.add_libro %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Administracion
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'listar_productos' %}">listado producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'agregar_producto' %}">agregar producto</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
            {% endif %}
            </ul>
          </li>
        </ul>
        <div class="iconos">
          
          <li class="cuenta">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-transparent"><i class="bi bi-person-x" style="color:rgb(67, 68, 68);"></i></button>
            </form>
            {% else %}
              <a href="{% url 'login' %}"><i class="bi bi-person" style="color:rgb(67, 68, 68);"></i></a>
            {% endif %}
          </li>
          <li class="carro">
            <a href="{% url 'comprar' %}" id="carrito">
              <i class="bi bi-cart2" style="color:rgb(67, 68, 68);">
                 
              </i>
            </a>
          </li>
        </div>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Buscar Titulo, Autor, Isbn..."
            aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>
      </div>
    </div>
  </nav>
  <!--fin navbar-->
  <!--carousel-->
  <div id="carouselMyExample" class="carousel slide" data-bs-ride="carousel">
    <!--en el carousel-inner se indica lo que se mostrará-->
    <div class="carousel-inner">
      <!--por cada imágen necesito un item e indico cual es la primera con active-->
      <div class="carousel-item active" data-bs-interval="5000">
        <!--si quiero le indico el tipo de display class="d-block w-100"-->
        <img src="{% static 'app/img/anuncio6.jpg' %}" class="imgCarrousel" alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="5000">
        <img src="{% static 'app/imagenes/ventas.png' %}" class="imgCarrousel" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselMyExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselMyExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
    <br id="Ofertas">
    <!--fc-->
  <nav>
    <!--cards-->
    
    <div class="containers">
      
      <center>
        <h1 class="texto">Ofertas</h1>
      </center>
      {%load humanize%}
      

      <div class="card__container" id="lista-compra">
        <article class="card__article">
          <img src="{% static 'app/imagenes/invierte en ti.jpg' %}" alt="" class="card__img">
  
          <div class="card__data">
            <span class="card__description">Natalia de Santiago</span>
            <h2 class="card__title">Invierte en ti</h2>
            <p class="precio">$11.000</p>
            <a href="#" class="card__button">Mas info</a>
            <button class="card__button2" data-id="2">add to cart</button>
          </div>
        </article>

        <article class="card__article">
          <img src="{% static 'app/imagenes/pedro-lemebel-tengo-miedo-torero (1).jpg' %}" alt="" class="card__img">
  
          <div class="card__data">
            <span class="card__description">Pedro Lemebel</span>
            <h2 class="card__title">Tengo miedo torero</h2>
            <p class="precio">$11.000</p>
            <a href="#" class="card__button">Mas info</a>
            <button class="card__button2" data-id="2">add to cart</button>
          </div>
        </article>

        <article class="card__article">
          <img src="{% static 'app/imagenes/crimen.png' %}" alt="" class="card__img">

          <div class="card__data">
            <span class="card__description">Fyodor Dostoevsky</span>
            <h2 class="card__title">Crimen y castigo</h2>
            <p class="precio">$11.000</p>
            <a href="#" class="card__button">Mas info</a>
            <button class="card__button2" data-id="2">add to cart</button>
          </div>
        </article>
        
      </div>
      <br id="Novedades">
      <br>
      <br>
      <!-- NOVEDADES -->
      <center>
        <h1 class="texto">Novedades</h1>
      </center>
      <div class="conteiner">
        <div style=" float:right;">
          
          {% include "carro/widget.html" %}
        </div>
      </div>
      <br>
      {%load humanize%}
      
      <div class="card__container" id="lista-compra">
        {%for p in productos %}
            <article class="card__article">
              <img src="{{ p.imagen.url}}" alt="" class="card__img">

              <div class="card__data">
                <span class="card__description">{{p.autor | capfirst}}</span>
                <h2 class="card__title">{{p.titulo | title}}</h2>
                <p class="precio">${{p.precio | intcomma}}</p>
                <a href="{% url 'libro1' %}" class="card__button">Mas info</a>
                <a href="{% url 'carro:agregar' p.id %}" class="card__button2">add to cart</a>
            
              </div>
            </article>
        {% endfor %}
        
      </div>
    </div>
  </nav>
  <br>
  <!--fin cards-->
  <!--Footer-->
  <div>
    <footer class="footer">
      <div class="container">
        <div class="footer-row">
          <div class="footer-links">
            <h4>Empresa</h4>
            <ul>
              <li><a href="{% url 'Nosotros' %}">Nosotros</a></li>
              <li><a href="#">Nuestros servicios</a></li>
              <li><a href="#">Politica de privacidad</a></li>
              <li><a href="{% url 'formulario' %}">Afiliate</a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Ayuda</h4>
            <ul>
              <li><a href="#">Preguntas Frecuentes</a></li>
              <li><a href="#">Compras</a></li>
              <li><a href="#">Envios</a></li>
              <li><a href="#">Pago</a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Encuentranos</h4>
            <ul>
              <li><a href="{% url 'ubicacion' %}">Av.Valparaiso 429</a></li>
              <li><a href="#">librarium@gmail.com</a></li>
              <li><a href="#"></a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>Siguenos</h4>
            <div class="social-link">
              <a href="#"><i class="bi bi-facebook"></i></a>
              <a href="#"><i class="bi bi-whatsapp"></i></a>
              <a href="#"><i class="bi bi-twitter-x"></i></a>
              <a href="#"><i class="bi bi-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <script src="{% static 'app/JS/carrito.js' %}"></script>
</body>

</html>